version: "3.9"

volumes:
  mysql_data2:
  tpcds-data:
    external: true

services:
  mysql:
    image: bitnami/mysql:latest
    container_name: mysql_ds
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
      # CLI flags that must be active *before* the .cnf is parsed
      MYSQL_EXTRA_FLAGS: |
        --secure-file-priv=/data
        --local-infile=ON
        --skip-log-bin                  # no binary log = no fsync per txn
        --innodb_doublewrite=0
        --innodb_flush_log_at_trx_commit=0
        --sync_binlog=0
    ports:
      - "3308:3306"
    volumes:
      - mysql_data2:/var/lib/mysql
      - ./custom-mysql.cnf:/etc/mysql/conf.d/zzz_custom.cnf:ro
      - tpcds-data:/data
    # Lift the ulimit so MySQL can keep many files open without kernel trips
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

